# Generated by Django 4.0.3 on 2022-04-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, help_text='Email Address', max_length=100)),
                ('full_name', models.CharField(help_text='First Name', max_length=100)),
            ],
        ),
    ]
