# Generated by Django 4.0.3 on 2022-04-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_religion_alter_subscribers_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='subscribers',
            name='hobbies',
            field=models.ManyToManyField(to='subscribers.hobbies'),
        ),
    ]
